server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/artyomtereshchenko/Java/dworkin-spring/config-service/src/main/resources/config
  profiles:
    active: native